#!/usr/bin/env python3
"""gen_timing386.py - src/cpu/timing386_ops.h from tools/ref86box/ops386.json.

    py tools/ref86box/gen_timing386.py

The 386DX/33 timing profile's per-opcode costs (tools/ref86box/timing386.md) as C tables: one entry per
(opcode, ModRM reg field) for one-byte opcodes, one per two-byte 0F opcode and one per string opcode
after REP. Each entry has the CLOCK_CYCLES 86Box charges for the register and memory forms and its
PREFETCH_RUN arguments, whether it flushes the queue, and a kind for the costs that depend on data,
which src/cpu/timing386.c computes itself. Run it after ops386.json changes; the header is committed.
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))

# kinds, matching timing386.h
KINDS = ["T386_NORMAL", "T386_JCC", "T386_LOOP", "T386_JCXZ", "T386_REPSTR", "T386_INTO", "T386_HLT",
         "T386_ENTER", "T386_UD", "T386_SHIFTN", "T386_NOTIMED"]
INSTR_TOTAL, INSTR_ELAPSED = -1, -2          # PREFETCH_RUN's instr_cycles: the handler's cycles / cycles_old - cycles


def num(v, default=0):
    if isinstance(v, int):
        return v
    if v is None:
        return default
    m = re.match(r"\s*(\d+)", str(v))
    return int(m[1]) if m else default


def pf(v, cycles):
    """PREFETCH_RUN arguments as [instr, bytes, modrm, reads, reads_l, writes, writes_l]; None for no run."""
    if v is None:
        return None
    if isinstance(v, dict):
        v = v.get("not_taken") or v.get("no_trap") or next(iter(v.values()))
    instr = v[0]
    if instr == "total_cycles" or instr == "instr_cycles":
        instr = INSTR_TOTAL
    elif instr == "cycles_old - cycles":
        instr = INSTR_ELAPSED
    else:
        instr = num(instr, cycles)
    modrm = 0 if v[2] in (-1, "-1") else 1
    rest = [0 if isinstance(x, str) else int(x) for x in v[3:7]]
    return [instr, int(v[1]), modrm] + rest


def kind(e):
    op, name, dyn = e["op"], e.get("name", ""), (e.get("dynamic") or "")
    cr = e.get("cycles_reg")
    if isinstance(cr, str) and "#UD" in cr:
        return "T386_UD"
    base = op.split()[-1].split("/")[0]
    if op.startswith(("F3 ", "F2 ")):
        return "T386_REPSTR"
    if len(op) == 2 and 0x70 <= int(op, 16) <= 0x7F or op.startswith("0F 8"):
        return "T386_JCC"
    if op in ("E0", "E1", "E2"):
        return "T386_LOOP"
    if op == "E3":
        return "T386_JCXZ"
    if op == "CE":
        return "T386_INTO"
    if op == "F4":
        return "T386_HLT"
    if op == "C8":
        return "T386_ENTER"
    if op.split("/")[0] in ("C0", "C1", "D2", "D3"):
        return "T386_SHIFTN"
    if e.get("prefetch_reg") is None and e.get("prefetch_mem") is None:
        return "T386_NOTIMED"
    return "T386_NORMAL"


def entry(e):
    cr, cm = num(e.get("cycles_reg")), num(e.get("cycles_mem"))
    if isinstance(e.get("cycles_reg"), str) and e["cycles_reg"].startswith("70 + "):
        cr, cm = 70 + int(e["cycles_reg"].split("+")[1]), 70 + int(e["cycles_mem"].split("+")[1])
    pr, pm = pf(e.get("prefetch_reg"), cr), pf(e.get("prefetch_mem"), cm)
    fl = e.get("flush")
    flush = 1 if fl is True else 2 if fl == "when taken" else 0
    per = num(e.get("cycles_per_element"))
    return dict(k=kind(e), c=(cr, cm), p=(pr, pm), flush=flush, per=per, name=e.get("name", ""))


def c_entry(x):
    def p(v):
        return "{%d,%s}" % (0 if v is None else 1, ",".join(str(i) for i in (v or [0] * 7)))
    return "{%s,{%d,%d},{%s,%s},%d,%d}" % (x["k"], x["c"][0], x["c"][1], p(x["p"][0]), p(x["p"][1]),
                                         x["flush"], x["per"])


def main():
    d = json.load(open(os.path.join(HERE, "ops386.json")))
    one = [[None] * 8 for _ in range(256)]
    of = [None] * 256
    rep = [None] * 256
    for e in d:
        op = e["op"]
        if op.startswith(("F3 ", "F2 ")):
            b = int(op.split()[1], 16)
            if op.startswith("F3 ") or rep[b] is None:
                rep[b] = entry(e)
        elif op.startswith("0F "):
            b = int(op.split()[1].split("/")[0], 16)
            if of[b] is None:
                of[b] = entry(e)
        else:
            b, _, r = op.partition("/")
            b = int(b, 16)
            regs = [int(r)] if r else range(8)
            for g in regs:
                one[b][g] = entry(e)
    ud = dict(k="T386_UD", c=(70, 70), p=(None, None), flush=0, per=0, name="(none)")
    out = ["/* timing386_ops.h - generated by tools/ref86box/gen_timing386.py from ops386.json; do not edit.",
           " * 86Box's 386DX costs (tools/ref86box/timing386.md): {kind, {cycles reg, mem}, {prefetch reg, mem:",
           " * {has run, instr (-1 the handler's cycles, -2 cycles_old - cycles), bytes, modrm, reads, reads_l,",
           " * writes, writes_l}}, flush (1 always, 2 when taken), cycles per string element}. */",
           "static const t386_op_t t386_one[256][8] = {"]
    for b in range(256):
        out.append("    /* %02X */ {%s}," % (b, ",".join(c_entry(x or ud) for x in one[b])))
    out.append("};")
    out.append("static const t386_op_t t386_0f[256] = {")
    for b in range(256):
        out.append("    /* 0F %02X */ %s," % (b, c_entry(of[b] or ud)))
    out.append("};")
    out.append("static const t386_op_t t386_rep[256] = {")
    for b in range(256):
        out.append("    /* REP %02X */ %s," % (b, c_entry(rep[b] or ud)))
    out.append("};")
    path = os.path.join(ROOT, "src", "cpu", "timing386_ops.h")
    open(path, "w", newline="\n").write("\n".join(out) + "\n")
    print("wrote", path)


if __name__ == "__main__":
    main()
