#!/usr/bin/env python3
"""Generate src/host/font8x16.h: the 256 CP437 glyphs, 8x16, from GNU Unifont.

The text screens (SETUP, DOS messages) need the PC character set. The VGA
ROM font is IBM's and is not shipped here; GNU Unifont (dual-licensed GPL-2+
with the font exception and SIL OFL 1.1, both compatible with this
project's GPL-3) has halfwidth 8x16 glyphs for every CP437 code point except
a few of the symbols in 0x01-0x1F, which are full-width there and are
narrowed here by taking every other column.

    py tools/gen_font.py unifont-16.0.04.hex.gz > src/host/font8x16.h
"""
import gzip
import sys

# CP437's display glyphs for the control range, as Unicode.
LOW = ("\u0000☺☻♥♦♣♠•◘○◙♂♀♪♫☼"
       "►◄↕‼¶§▬↨↑↓→←∟↔▲▼")


def cp437_char(i):
    if i < 0x20:
        return LOW[i]
    if i == 0x7F:
        return "⌂"
    return bytes([i]).decode("cp437")


def main():
    path = sys.argv[1]
    opener = gzip.open if path.endswith(".gz") else open
    glyphs = {}
    with opener(path, "rt") as f:
        for line in f:
            cp, _, bits = line.strip().partition(":")
            glyphs[int(cp, 16)] = bits
    out = []
    for i in range(256):
        ch = cp437_char(i)
        bits = glyphs.get(ord(ch), "") if i else "0" * 32
        if len(bits) == 32:
            rows = [int(bits[r * 2:r * 2 + 2], 16) for r in range(16)]
        elif len(bits) == 64:
            rows = []
            for r in range(16):
                w = int(bits[r * 4:r * 4 + 4], 16)
                b = 0
                for k in range(8):
                    if w & (0x8000 >> (2 * k)) or w & (0x8000 >> (2 * k + 1)):
                        b |= 0x80 >> k
                rows.append(b)
        else:
            rows = [0] * 16
        out.append(rows)
    print("/* font8x16.h - the CP437 character set, 8x16, generated by tools/gen_font.py")
    print(" * from GNU Unifont 16.0.04 (GPL-2+ with font exception / SIL OFL 1.1). */")
    print("#ifndef F117R_FONT8X16_H")
    print("#define F117R_FONT8X16_H")
    print("static const unsigned char FONT8X16[256][16] = {")
    for i, rows in enumerate(out):
        print("    {" + ",".join("0x%02X" % r for r in rows) + "},  /* %02X */" % i)
    print("};")
    print("#endif")


if __name__ == "__main__":
    main()
